/**
 * CCA auction library. Coin page imports this for the cca-branch flow.
 */
export { ccaAbi } from "./abi/cca";
export { ccaLensAbi } from "./abi/ccaLens";
export { lbpStrategyAbi } from "./abi/lbpStrategy";
export { launchpadCcaAbi, lockerCcaAbi, poolManagerAbi, positionManagerAbi } from "./abi/launchpadCca";
export { universalRouterAbi } from "./abi/universalRouter";
export {
  CCA_SEPOLIA,
  FUNDS_RECIPIENT,
  missingCcaProductKeys,
  resolveCcaProductAddresses,
  type CcaProductAddresses,
} from "./addresses";
export {
  AUCTION_BLOCKS,
  AUCTION_STEPS_MPS_TOTAL,
  CCA_CONFIG,
  FIRST_BID_ID,
  FLOOR_PRICE_Q96,
  GRADUATION_ETH_WEI,
  NATIVE_ETH,
  POOL_FEE,
  POOL_TICK_SPACING,
  PROPHET_FEE_SHARE,
  PROTOCOL_FEE_SHARE,
  Q96,
  SEPOLIA_BLOCK_SECONDS,
  TICK_SPACING_Q96,
  WAD,
  auctionClaimBlock,
  auctionEndBlock,
  auctionMigrationBlock,
  packUniformAuctionSteps,
  resolveCcaConfig,
  type CcaConfig,
} from "./config";
export {
  CCA_BID_ERROR_COPY,
  CCA_CLAIM_ERROR_COPY,
  CCA_COPY,
  CCA_ERROR_COPY,
  CCA_EXIT_ERROR_COPY,
  CCA_FEE_ERROR_COPY,
  CCA_LAUNCH_ERROR_COPY,
  CCA_LAUNCH_ERROR_MESSAGE,
  CCA_LAUNCH_ERROR_NAMES,
  CCA_MIGRATE_ERROR_COPY,
  CCA_SWAP_ERROR_COPY,
  FEE_COLLECT_COPY,
  MISSING_ADDRESS_COPY,
  SWAP_SECTION_COPY,
  auctionLiveCopy,
  auctionStatusCopy,
  auctionStatusSubCopy,
  blocksToMmSs,
  ccaErrorCopy,
  claimBlockedCopy,
  departedReplacesAuctionStatus,
  exitCtaCopy,
  exitDoneCopy,
  exitHelpCopy,
  feeCollectCopy,
  formatMmSs,
  getEthBackCopy,
  graduationGoalWei,
  officialCcaErrorName,
  openMarketBeforeCopy,
  raisedProgressCopy,
  refundUnusedCopy,
  swapSectionCopy,
  swapStepCopy,
  swapTokenLine,
  yourBidCopy,
  type AuctionCopyStatus,
  type CcaErrorCopyVars,
  type CcaOfficialErrorName,
} from "./copy";
export { ccaErrorCopyFor, ccaUserMessage, errorText, mapCcaError, type CcaErrorKind } from "./errors";
export {
  auctionActionVisibility,
  auctionScheduleRequest,
  bidRead,
  blocksRemaining,
  canOpenMarket,
  ccaLensStateRequest,
  deriveAuctionCopyStatus,
  deriveAuctionView,
  goalNotReachedEffects,
  isAuctionFinalized,
  isAuctionSoldOut,
  readAuctionLensState,
  readAuctionView,
  type AuctionActionVisibility,
  type AuctionPhase,
  type AuctionState,
  type AuctionView,
  type CcaBid,
  type CcaCheckpoint,
  type CcaLensState,
  type Checkpoint,
} from "./auction";
export { placeBid, placeBidArgs, placeBidWrite, type PlaceBidInput } from "./bid";
export { claimTokens, claimTokensBatch, claimTokensBatchWrite, claimTokensWrite } from "./claim";
export { checkpoint, checkpointWrite } from "./checkpoint";
export {
  exitBid,
  exitBidWrite,
  exitPartiallyFilledBid,
  exitPartiallyFilledBidWrite,
} from "./exit";
export {
  migrateOutcomeFromReceipt,
  openMarket,
  openMarketResult,
  openMarketWrite,
  type MigrateOutcome,
} from "./migrate";
export {
  PERMIT2,
  SETTLE_ALL,
  SWAP_EXACT_IN_SINGLE,
  TAKE_ALL,
  UNIVERSAL_ROUTER,
  V4_SWAP_COMMAND,
  approvePermit2ForRouter,
  approveTokenForPermit2,
  decodeV4ExactInSingle,
  encodeUniversalRouterExecute,
  encodeV4ExactInSingle,
  ethTokenPoolKey,
  permit2Abi,
  permit2ApproveRouterWrite,
  swapExactInSingle,
  swapExactInSingleWrite,
  tokenApprovePermit2Write,
  v4SwapActions,
  v4SwapCommands,
  type EncodedV4ExactInSingle,
  type ExactInSingleInput,
  type V4PoolKey,
} from "./swap";
export {
  INTERFACE_CCA_PENDING,
  INTERFACE_CCA_TBD,
  InterfaceCcaPendingError,
  auctionOfRead,
  backendLaunchErrorNames,
  collectCcaWrite,
  hookRead,
  initializeDistributionSalt,
  initializerFromAuction,
  isGraduatedRead,
  launchCcaWrite,
  lbpStrategyRead,
  lockerCollectActionBytes,
  lockerRead,
  lockerTokenIdBinding,
  positionManagerRead,
  withdrawAccruedWrite,
} from "./launchpadCca";
export {
  fetchPositionManagerMintLogs,
  findLockerTokenId,
  findLockerTokenIdReads,
  lockerProphetOfRead,
  matchLockerTokenId,
  matchMintedTokenId,
  positionManagerMintLogsQuery,
  positionManagerTransferAbi,
  registerLocker,
  registerLockerWrite,
  tokenIdFromMigrateReceipt,
  tokenIdOfRead,
  tokenIdsMintedToLocker,
} from "./register";
export {
  MaxPriceBelowFloorError,
  alignPriceToTick,
  bidAmountQ96ToWei,
  budgetEthToAmount,
  ethPerTokenToQ96,
  prevTickHintQ96,
  q96ToEthPerToken,
  q96ToWeiPerToken,
  snapMaxPriceToTick,
  weiPerTokenToQ96,
} from "./price";
export {
  assertSuccessfulReceipt,
  sendCcaWrite,
  sendCcaWriteResult,
  type CcaReceipt,
  type CcaWriteOptions,
  type CcaWriteRequest,
  type CcaWriteResult,
} from "./writes";
export {
  bidExitedLogsQuery,
  bidSubmittedLogsQuery,
  ccaEventLogsQuery,
  ccaLogsFromBlock,
  fetchCcaEventLogs,
  tokensClaimedLogsQuery,
  type CcaAuctionEvent,
} from "./logs";
export { CCA_FORK_PIN_BLOCK, CCA_FORK_STEPS, forkHappyPathSchedule } from "./flow";
